name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull and run Ollama Docker container
      run: |
        docker run -d --name ollama -p 8080:8080 ollama/ollama:latest
        sleep 10 # Wait for the container to be fully up and running

    - name: Verify Ollama installation
      run: docker exec ollama ollama --version

    - name: Run tests
      run: cd v2 && go test -run PullGemmaIntegration -run Stream -v
